In [122]:
import mltools as ml
import numpy as np
import matplotlib.pyplot as plt

In [182]:
X = np.genfromtxt('data/X_train.txt', delimiter=None)
Y = np.genfromtxt('data/Y_train.txt', delimiter=None)

In [183]:
print(X)
print(X.shape)

[[3.2826e+00 0.0000e+00 0.0000e+00 ... 6.0066e+00 0.0000e+00 2.4000e+02]
 [6.8284e+00 0.0000e+00 1.0310e+03 ... 2.2922e+00 0.0000e+00 2.2500e+02]
 [7.1572e+00 0.0000e+00 1.1820e+03 ... 1.4422e+00 1.8500e+01 2.2200e+02]
 ...
 [8.0281e+00 0.0000e+00 3.5990e+03 ... 6.7823e-01 0.0000e+00 2.2100e+02]
 [9.9802e+00 9.9100e+02 4.3920e+03 ... 7.3485e-01 6.1500e+01 2.1500e+02]
 [5.4192e+00 0.0000e+00 9.0000e+00 ... 3.8076e+00 0.0000e+00 2.3300e+02]]
(200000, 14)


In [184]:
print(Y.astype(int))
print(Y.shape)
print(type(Y))

[1 0 0 ... 1 1 0]
(200000,)
<class 'numpy.ndarray'>


In [185]:
Xtr, Ytr = X[:10000], Y[:10000]
Xva, Yva = X[10000:20000], Y[10000:20000]

In [186]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='adam',random_state=1, hidden_layer_sizes= (24,9), max_iter=300).fit(Xtr, Ytr)

In [187]:
clf.score(Xva, Yva)

0.5769

In [188]:
Xte = np.genfromtxt('data/X_test.txt', delimiter=None)
Yte = np.vstack((np.arange(Xte.shape[0]), clf.predict_proba(Xte)[:,1])).T
np.savetxt('Y_submit.txt',Yte,'%d, %.2f',header='ID,Prob1',comments='',delimiter=',')

In [189]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier

In [190]:
Xtr = X[:10000]
Ytr = Y[:10000]
Xva = X[10000:20000]
Yva = Y[10000:20000]
gbc = GradientBoostingClassifier(n_estimators=500, min_samples_leaf = 5, learning_rate=0.1, max_depth=5, random_state=1).fit(Xtr, Ytr)
gbc.score(Xva, Yva)

0.7052

In [191]:
import csv 
filename = "mlp_submit.csv"
fields = [] 
rows = [] 
 
with open(filename, 'r') as csvfile: 
	csvreader = csv.reader(csvfile) 
	
	fields = next(csvreader) 
	for row in csvreader: 
		rows.append(row) 
        
mlp_predict = []
for prob in rows:
    mlp_predict.append(prob)


In [192]:
filename = "knn_submit.csv"
fields = [] 
rows = [] 
 
with open(filename, 'r') as csvfile: 
	csvreader = csv.reader(csvfile) 
	
	fields = next(csvreader) 
	for row in csvreader: 
		rows.append(row) 
        
knn_predict = []
for prob in rows:
    knn_predict.append(prob)

In [193]:
filename = "forest_submit.csv"
fields = [] 
rows = [] 
 
with open(filename, 'r') as csvfile: 
	csvreader = csv.reader(csvfile) 
	
	fields = next(csvreader) 
	for row in csvreader: 
		rows.append(row) 
        
forest_predict = []
for prob in rows:
    forest_predict.append(prob)

In [194]:
final_avg = []
final_max = []
#Average
for i in range(0,200000):
    avg = (float(forest_predict[i][1]) + float(knn_predict[i][1]) +float(mlp_predict[i][1]))/3
    mx = max(float(forest_predict[i][1]),float(knn_predict[i][1]),float(mlp_predict[i][1]))
    final_max.append(mx)
    final_avg.append(avg)
len(final_max)

200000

In [195]:
len(clf.predict_proba(Xte)[:,1])

200000

In [177]:
Xte = np.genfromtxt('data/X_test.txt', delimiter=None)
Yte = np.vstack((np.arange(Xte.shape[0]), final_max)).T
np.savetxt('Ymax_submit.txt',Yte,'%d, %.2f',header='ID,Prob1',comments='',delimiter=',')

In [178]:
Xte = np.genfromtxt('data/X_test.txt', delimiter=None)
Yte = np.vstack((np.arange(Xte.shape[0]), final_max)).T
np.savetxt('Yavg_submit.txt',Yte,'%d, %.2f',header='ID,Prob1',comments='',delimiter=',')